spring:
  application:
    name: eciComm

aws:
  region: us-east-1
  credentials:
    access-key: ASIAZMQOUQZAZT3LTKTP
    secret-key: vqpOhpqhix/A1a3s5oFpmtOsDlZZu2rg4d3DMAHR
  dynamodb:
    endpoint: https://dynamodb.${aws.region}.amazonaws.com
    tables:
      product: Products
      order: Orders
      orderItem: OrderItems
      inventory: Inventory
      user: Users
  s3:
    buckets:
      product: eciproductsbucket
      sagemaker: ecicommsagemakerbucket
  sagemaker:
    endpoint: EciCommSGK
    
  