spring:
  application:
    name: eciComm

aws:
  region: us-east-1
  credentials:
    access-key: ASIAZMQOUQZAQ55VABHB
    secret-key: nUgu8gP2McWUnfgnmhWZUb1ZnKTSEqnee12SOIcc
  dynamodb:
    endpoint: https://dynamodb.${aws.region}.amazonaws.com
    tables:
      product: Products
      order: Orders
      inventory: Inventory
      user: Users
  s3:
    bucket: eciproductsbucket